server {
    listen 80;
    listen [::]:80;
    server_name yuyirrr.com www.yuyirrr.com;

    root /var/www/yuyirrr/current;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
